import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ChakraProviders} from '@/providers/chakraProvider'
import StoreProvider from '@/providers/reduxProvider'
import { languages } from '@/i18n/settings'
import { LocaleProvider } from '@/providers/localeProvider'
import { headers } from "next/headers";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const lng = headers()?.get('accept-language')?.split(',')[0] || 'ja'

  return (
    <html lang={lng}>
      <body className={inter.className}>
        <LocaleProvider locale={lng}>
          <StoreProvider>
            <ChakraProviders >
              {children}
            </ChakraProviders>
          </StoreProvider>
        </LocaleProvider>
      </body>
    </html>
  )
}
