import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ChakraProviders} from '@/providers/chakraProvider'
import StoreProvider from '@/providers/reduxProvider'
import { dir } from 'i18next'
import { languages } from '@/app/i18n/settings'


export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {
    lng
  }
}: {
  children: React.ReactNode
  params: {
    lng: string
  }
}) {
  return (
    <html lang={lng}>
      <body className={inter.className}>
        <StoreProvider>
          <ChakraProviders >
            {children}
          </ChakraProviders>
        </StoreProvider>
      </body>
    </html>
  )
}
